import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

// Remove Navigation from layout to avoid build issues
// import ClientWrapper from "../components/ClientWrapper"
// import dynamic from 'next/dynamic'
// const Navigation = dynamic(() => import('../components/Navigation/Navbar'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <Script
      id='google-analytics'
      strategy="afterInteractive"
      dangerouslySetInnerHTML={{
        __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-J97S5LNPEZ', {
            page_path: window.location.pathname,
          });
        `,
        }}
      />
      <title>JLang Designs for 2024</title>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
