name: Build and Deploy JL Designs to Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Load .env.production file
        run: |
          echo "Loading .env.production file"
          set -a
          source .env.production
          set +a

      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_ENV: production

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JLDESIGNS }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg NEXT_PUBLIC_APP_ENV=production \
            $(grep -v '^#' .env.production | sed 's/^/--build-arg /') \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/jldesigns-app .

      - name: Configure Docker to use GCloud credentials
        run: |
          gcloud auth configure-docker gcr.io

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/jldesigns-app

      - name: Deploy to Cloud Run
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy jldesigns-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/jldesigns-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 4000 \
            --memory 8Gi \
            --cpu 4 \
            --min-instances 1 \
            --max-instances 3 \
            --concurrency 80 \
            --timeout 300s \
            --set-env-vars=HOST=jldesigns.com \
            $(grep -v '^#' .env.production | sed 's/^/--set-env-vars=/')

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JLDESIGNS }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Set Firebase Configurations
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase functions:config:set artifactregistry.enabled=false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          DOTENV_CONFIG_PATH: .env.production

      - name: Deploy to Firebase Hosting
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase deploy --only hosting:production --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          DOTENV_CONFIG_PATH: .env.production