name: Build and Deploy JL Designs to Dev Environment

on:
  push:
    branches:
      - 'feature/**'
      - 'develop'

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Load .env.development file
        run: |
          echo "Loading .env.development file"
          set -a
          source .env.development
          set +a

      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_ENV: development

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JLDESIGNS_DEV }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}

      - name: Configure Docker to use GCloud credentials
        run: |
          gcloud auth configure-docker gcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build Docker image
        run: |
          # Validate required secrets
          if [[ -z "${{ secrets.GCP_PROJECT_ID_DEV }}" ]]; then
            echo "Error: GCP_PROJECT_ID_DEV secret is not set"
            exit 1
          fi
          
          # Build environment arguments from .env file
          BUILD_ARGS=""
          if [ -f .env.development ]; then
            while IFS= read -r line; do
              if [[ ! -z "$line" && ! "$line" =~ ^#.* ]]; then
                BUILD_ARGS="$BUILD_ARGS --build-arg $line"
              fi
            done < .env.development
          fi
          
          # Build the Docker image
          docker build \
            --build-arg NEXT_PUBLIC_APP_ENV=development \
            $BUILD_ARGS \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/jldesigns-app-dev:dev \
            .

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/jldesigns-app-dev:dev

      - name: Deploy to Cloud Run
        run: |
          # Build environment variables from .env file
          ENV_VARS="HOST=dev.jldesigns.com"
          if [ -f .env.development ]; then
            while IFS= read -r line; do
              if [[ ! -z "$line" && ! "$line" =~ ^#.* ]]; then
                ENV_VARS="$ENV_VARS,$line"
              fi
            done < .env.development
          fi
          
          gcloud run deploy jldesigns-app-dev \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/jldesigns-app-dev:dev \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 4000 \
            --memory 8Gi \
            --cpu 4 \
            --min-instances 1 \
            --max-instances 2 \
            --concurrency 80 \
            --timeout 300s \
            --set-env-vars="$ENV_VARS"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set Firebase Configurations
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
        env:
          DOTENV_CONFIG_PATH: .env.development

      - name: Deploy to Firebase Hosting
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase deploy --only hosting:development --debug
        env:
          DOTENV_CONFIG_PATH: .env.development